LEFT 13, RIGHT 00

In [1]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L13.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R00.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(585, 71), (590, 91), (598, 77), (604, 65), (592, 107), (600, 94), (605, 84), (613, 73), (621, 60), (595, 124), (627, 288), (640, 296), (640, 290), (642, 284), (652, 302), (653, 297), (656, 292), (656, 287), (658, 279), (664, 311)]
], dtype=np.float32)

points_2 = np.array([
    [(177, 86), (183, 104), (188, 94), (196, 84), (186, 122), (193, 112), (198, 103), (204, 92), (215, 80), (189, 140), (226, 296), (236, 304), (237, 298), (239, 290), (244, 308), (246, 303), (248, 296), (252, 289), (252, 284), (254, 314)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL13R00.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL13R00.png', img1_warped_contrast)  # Warped Image 1 저장

# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.97    0.01 -387.32]
 [  -0.00    0.93   25.64]]
Homography Matrix:
 [[  -2.83    0.00 1311.45]
 [  -0.99   -1.88  546.92]
 [  -0.01    0.00    1.00]]
Rotation Matrix R:
 [[ 0.96 -0.29 -0.00]
 [ 0.29  0.96  0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.04]
 [-0.09]
 [16.76]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-751.44]
 [-313.38]
 [  -1.57]]


LEFT 14, RIGHT 01

In [2]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L14.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R01.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(557, 75), (561, 91), (568, 79), (576, 67), (564, 109), (571, 98), (580, 88), (584, 76), (592, 65), (566, 127), (599, 288), (610, 294), (610, 288), (614, 283), (622, 303), (624, 293), (625, 288), (627, 283), (629, 277), (636, 307)]
], dtype=np.float32)

points_2 = np.array([
    [(154, 84), (156, 102), (164, 91), (173, 80), (160, 120), (167, 110), (176, 100), (183, 89), (188, 80), (163, 136), (200, 297), (209, 303), (211, 298), (213, 292), (220, 308), (221, 301), (223, 298), (226, 292), (229, 283), (231, 314)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL14R01.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL14R01.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   1.03    0.00 -423.60]
 [   0.08    0.97  -30.54]]
Homography Matrix:
 [[    3.90    -0.13 -1697.79]
 [    0.69     2.91  -342.80]
 [    0.00    -0.00     1.00]]
Rotation Matrix R:
 [[ 0.99 -0.17 -0.00]
 [ 0.17  0.99  0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.02]
 [-0.05]
 [ 9.54]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-589.84]
 [-119.09]
 [  -0.65]]


LEFT 15, RIGHT 02

In [3]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L15.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R02.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(536, 76), (540, 93), (547, 81), (553, 70), (543, 110), (549, 97), (554, 89), (562, 78), (571, 66), (542, 126), (574, 288), (587, 295), (589, 287), (591, 280), (599, 301), (600, 294), (600, 288), (604, 282), (607, 275), (612, 306)]
], dtype=np.float32)

points_2 = np.array([
    [(128, 80), (132, 104), (138, 92), (148, 82), (136, 116), (144, 108), (149, 98), (158, 89), (165, 76), (140, 135), (180, 296), (187, 304), (189, 297), (192, 292), (198, 308), (200, 304), (204, 298), (206, 292), (208, 284), (209, 314)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees)")
print("라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL15R02.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL15R02.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   1.19   -0.02 -508.94]
 [   0.02    0.99    2.59]]
Homography Matrix:
 [[   1.94    0.30 -864.49]
 [   0.32    2.04 -193.69]
 [   0.00    0.00    1.00]]
Rotation Matrix R:
 [[ 0.99 -0.16 -0.00]
 [ 0.16  0.99 -0.00]
 [ 0.00  0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees)
라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[ 0.03]
 [-0.02]
 [ 9.19]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-447.98]
 [-100.37]
 [  -0.48]]


LEFT 16, RIGHT 03

In [4]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L16.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R03.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(514, 76), (515, 95), (523, 83), (531, 72), (518, 111), (524, 101), (531, 90), (538, 78), (546, 67), (519, 127), (551, 288), (562, 293), (565, 286), (567, 280), (572, 299), (575, 293), (577, 289), (580, 281), (580, 276), (585, 305)]
], dtype=np.float32)

points_2 = np.array([
    [(98, 77), (103, 100), (112, 88), (120, 76), (108, 117), (115, 103), (123, 94), (130, 84), (138, 74), (112, 133), (150, 298), (160, 305), (164, 298), (166, 292), (172, 311), (174, 304), (175, 299), (178, 293), (179, 287), (184, 316)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL16R03.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL16R03.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   1.02    0.04 -421.88]
 [   0.02    1.03   -7.97]]
Homography Matrix:
 [[    3.28     0.11 -1437.29]
 [    0.63     2.78  -335.81]
 [    0.00     0.00     1.00]]
Rotation Matrix R:
 [[ 0.98 -0.18 -0.00]
 [ 0.18  0.98  0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.00]
 [-0.05]
 [10.23]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-534.49]
 [-124.88]
 [  -0.63]]


LEFT 17, RIGHT 04

In [5]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L17.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R04.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(487, 80), (490, 97), (496, 85), (504, 74), (491, 113), (499, 101), (505, 91), (512, 79), (520, 68), (494, 131), (523, 285), (534, 295), (537, 287), (538, 280), (546, 300), (547, 293), (549, 287), (549, 281), (552, 275), (557, 305)]
], dtype=np.float32)

points_2 = np.array([
    [(74, 75), (77, 95), (85, 83), (93, 71), (80, 114), (88, 103), (96, 93), (104, 84), (112, 70), (85, 130), (126, 299), (137, 306), (137, 300), (141, 293), (148, 311), (148, 304), (150, 300), (154, 294), (156, 285), (158, 317)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL17R04.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL17R04.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   1.14    0.03 -483.14]
 [   0.17    1.03  -86.58]]
Homography Matrix:
 [[   10.82     0.93 -4775.72]
 [    3.65     9.94 -1997.11]
 [    0.01     0.00     1.00]]
Rotation Matrix R:
 [[ 0.95 -0.30 -0.00]
 [ 0.30  0.95 -0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.00]
 [-0.06]
 [17.46]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-539.86]
 [-225.76]
 [  -0.89]]


LEFT 18, RIGHT 05

In [6]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L18.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R05.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(453, 79), (456, 97), (463, 85), (470, 75), (457, 116), (464, 104), (474, 93), (478, 82), (485, 71), (461, 130), (492, 285), (500, 293), (502, 286), (504, 280), (511, 299), (514, 292), (516, 286), (518, 280), (518, 274), (523, 304)]
], dtype=np.float32)

points_2 = np.array([
    [(46, 72), (50, 92), (60, 82), (67, 70), (56, 110), (64, 99), (71, 88), (77, 79), (87, 68), (57, 128), (100, 299), (110, 306), (114, 300), (118, 292), (121, 311), (125, 306), (126, 300), (129, 293), (132, 289), (135, 318)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL18R05.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL18R05.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   1.26    0.03 -525.04]
 [   0.11    1.07  -62.90]]
Homography Matrix:
 [[   1.20    0.04 -490.00]
 [   0.14    1.17  -71.86]
 [   0.00   -0.00    1.00]]
Rotation Matrix R:
 [[ 0.99 -0.11 -0.00]
 [ 0.11  0.99  0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.01]
 [-0.02]
 [ 6.36]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-424.33]
 [ -62.23]
 [  -0.13]]


LEFT 19, RIGHT 06

In [7]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L19.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R06.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(443, 81), (445, 99), (454, 86), (459, 76), (449, 114), (455, 104), (462, 93), (468, 82), (474, 71), (449, 130), (481, 286), (489, 292), (493, 286), (494, 279), (502, 298), (502, 291), (504, 286), (505, 281), (507, 275), (512, 303)]
], dtype=np.float32)

points_2 = np.array([
    [(11, 69), (16, 87), (24, 78), (33, 65), (21, 107), (29, 94), (35, 87), (43, 75), (52, 63), (24, 124), (68, 302), (80, 309), (83, 301), (86, 292), (91, 313), (94, 305), (98, 300), (101, 293), (103, 286), (104, 318)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL19R06.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL19R06.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   1.27    0.04 -554.95]
 [   0.11    1.09  -66.95]]
Homography Matrix:
 [[   1.86    0.03 -808.39]
 [   0.21    1.47 -109.80]
 [   0.00   -0.00    1.00]]
Rotation Matrix R:
 [[ 0.99 -0.10 -0.00]
 [ 0.10  0.99  0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.02]
 [-0.03]
 [ 5.96]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-554.98]
 [ -75.38]
 [  -0.31]]


LEFT 20, RIGHT 07

In [8]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L20.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R07.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(620, 26), (621, 42), (628, 36), (636, 25), (621, 57), (629, 50), (635, 42), (642, 34), (649, 24), (622, 71), (453, 285), (462, 293), (464, 287), (466, 279), (472, 299), (474, 293), (475, 286), (479, 282), (480, 274), (483, 303)]
], dtype=np.float32)

points_2 = np.array([
    [(220, 51), (220, 64), (226, 59), (232, 52), (223, 79), (228, 73), (233, 67), (238, 60), (245, 53), (223, 93), (44, 301), (57, 308), (60, 301), (62, 295), (68, 313), (70, 307), (75, 301), (76, 294), (79, 288), (81, 320)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL20R07.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL20R07.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   1.31    0.20 -606.14]
 [  -0.07    0.91   72.42]]
Homography Matrix:
 [[   1.57   -0.05 -634.45]
 [   0.23    1.36 -103.38]
 [   0.00   -0.00    1.00]]
Rotation Matrix R:
 [[ 0.99 -0.15 -0.00]
 [ 0.15  0.99  0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.01]
 [-0.03]
 [ 8.37]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-468.72]
 [ -76.38]
 [  -0.26]]


LEFT 21, RIGHT 08

In [9]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L21.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R08.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(598, 30), (599, 45), (606, 37), (612, 28), (598, 60), (605, 52), (612, 45), (619, 36), (626, 27), (599, 75), (435, 287), (442, 291), (446, 286), (448, 279), (454, 297), (456, 291), (457, 286), (459, 281), (461, 274), (464, 302)]
], dtype=np.float32)

points_2 = np.array([
    [(193, 47), (194, 62), (201, 58), (207, 49), (196, 76), (201, 72), (207, 64), (212, 60), (219, 53), (198, 92), (11, 302), (23, 311), (28, 302), (32, 296), (36, 316), (39, 309), (41, 301), (45, 296), (46, 291), (49, 321)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL21R08.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL21R08.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   1.07   -0.00 -446.76]
 [   0.09    1.05  -35.75]]
Homography Matrix:
 [[    3.34    -0.05 -1397.73]
 [    1.17     3.44  -660.78]
 [    0.00     0.00     1.00]]
Rotation Matrix R:
 [[ 0.95 -0.32 -0.00]
 [ 0.32  0.95 -0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.00]
 [-0.05]
 [18.60]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-443.14]
 [-209.49]
 [  -0.68]]


LEFT 22, RIGHT 09

In [10]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L22.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R09.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
     [(571, 32), (572, 48), (578, 40), (585, 32), (572, 62), (579, 56), (585, 49), (590, 39), (598, 31), (572, 76), (624, 236), (624, 240), (626, 242), (627, 249), (631, 255), (639, 238), (641, 244), (641, 246), (644, 253), (646, 259)]
], dtype=np.float32)

points_2 = np.array([
    [(171, 45), (172, 60), (177, 55), (184, 48), (174, 77), (179, 68), (184, 64), (189, 55), (197, 49), (174, 90), (226, 245), (227, 251), (228, 253), (229, 256), (229, 263), (239, 251), (239, 254), (240, 257), (241, 262), (244, 268)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL22R09.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL22R09.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.87    0.03 -323.84]
 [   0.06    0.96  -16.59]]
Homography Matrix:
 [[   1.83    0.31 -770.16]
 [   0.50    1.90 -272.66]
 [   0.00    0.00    1.00]]
Rotation Matrix R:
 [[ 0.97 -0.25 -0.00]
 [ 0.25  0.97 -0.00]
 [ 0.00  0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[ 0.02]
 [-0.03]
 [14.69]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-455.43]
 [-161.24]
 [  -0.41]]
