In [7]:
import numpy as np

# 주어진 호모그래피 행렬 H
H = np.array([
    [66.32, 5.77, -28283.06],
    [15.13, 54.33, -8086.35],
    [0.09, 0.01, 1.00]
])

# SVD 분해
U, Sigma, VT = np.linalg.svd(H)

# 특이값 행렬 Sigma를 대각 행렬로 변환
Sigma_matrix = np.zeros((3, 3))
np.fill_diagonal(Sigma_matrix, Sigma)

# 결과 출력
print("U:\n", U)
print("\nΣ (Sigma):\n", Sigma_matrix)
print("\nV^T:\n", VT)


U:
 [[-0.961475  0.274894  0.000054]
 [-0.274894 -0.961475 -0.000066]
 [ 0.000034 -0.000078  1.      ]]

Σ (Sigma):
 [[29416.416735     0.           0.      ]
 [    0.          50.784567     0.      ]
 [    0.           0.           0.092842]]

V^T:
 [[-0.002309 -0.000696  0.999997]
 [ 0.072539 -0.997365 -0.000527]
 [ 0.997363  0.072538  0.002353]]
