LEFT 13, RIGHT 00

In [1]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L13.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R00.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(688, 271), (686, 278), (684, 284), (684, 291), (683, 297), (703, 274), (700, 278), (700, 286), (700, 291), (697, 297)]
], dtype=np.float32)

points_2 = np.array([
    [(274, 280), (273, 284), (271, 289), (270, 296), (269, 301), (287, 280), (286, 285), (283, 289), (283, 296), (283, 301)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL13R00.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL13R00.png', img1_warped_contrast)  # Warped Image 1 저장

# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.86   -0.03 -307.67]
 [  -0.04    0.85   78.20]]
Homography Matrix:
 [[ -0.10  -0.29 194.05]
 [ -0.24  -0.18 259.38]
 [ -0.00  -0.00   1.00]]
Rotation Matrix R:
 [[-0.18 -0.98  0.00]
 [-0.98  0.18  0.00]
 [-0.00 -0.00 -1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-114.82]
 [ 138.43]
 [   0.08]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[1368.14]
 [1828.74]
 [   8.05]]


LEFT 14, RIGHT 01

In [2]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L14.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R01.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(699, 237), (698, 224), (698, 212), (697, 199), (695, 183), (714, 232), (712, 219), (712, 206), (710, 192), (710, 178), (702, 249), (702, 256), (702, 260), (702, 266), (703, 273), (716, 245), (715, 249), (714, 256), (716, 261), (716, 267)]
], dtype=np.float32)

points_2 = np.array([
    [(286, 250), (285, 237), (284, 226), (282, 214), (282, 200), (296, 244), (295, 233), (295, 222), (295, 210), (293, 198), (288, 259), (288, 265), (288, 271), (287, 274), (286, 280), (299, 254), (298, 261), (298, 264), (297, 269), (297, 275)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL14R01.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL14R01.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.74    0.01 -235.05]
 [  -0.02    0.89   54.01]]
Homography Matrix:
 [[ -1.66   0.01 865.02]
 [ -0.73  -0.91 469.85]
 [ -0.00   0.00   1.00]]
Rotation Matrix R:
 [[ 0.95 -0.31 -0.00]
 [ 0.31  0.95  0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.02]
 [-0.08]
 [17.82]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-1062.07]
 [ -576.88]
 [   -2.23]]


LEFT 15, RIGHT 02

In [3]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L15.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R02.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(700, 230), (698, 215), (697, 202), (697, 189), (696, 175), (706, 219), (706, 206), (706, 193), (705, 179), (702, 165), (689, 243), (689, 250), (689, 257), (689, 261), (689, 267), (704, 239), (703, 245), (703, 249), (703, 256), (705, 260)]
], dtype=np.float32)

points_2 = np.array([
    [(286, 240), (285, 227), (285, 216), (284, 205), (283, 194), (292, 232), (291, 221), (290, 209), (289, 199), (287, 185), (281, 254), (279, 259), (279, 264), (279, 270), (278, 275), (289, 249), (290, 253), (289, 259), (290, 263), (290, 268)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees)")
print("라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL15R02.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL15R02.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.70    0.02 -205.47]
 [   0.16    0.86  -68.46]]
Homography Matrix:
 [[ -0.33   0.00 252.57]
 [ -0.28   0.07 196.59]
 [ -0.00   0.00   1.00]]
Rotation Matrix R:
 [[-0.58 -0.81  0.00]
 [-0.81  0.58 -0.00]
 [-0.00 -0.00 -1.00]]
Rotation Vector (Rodrigues) rvec (in degrees)
라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-82.46]
 [159.82]
 [ -0.23]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[4889.24]
 [3805.56]
 [  20.36]]


LEFT 16, RIGHT 03

In [4]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L16.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R03.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(698, 220), (697, 207), (696, 193), (696, 180), (695, 166), (710, 213), (710, 200), (710, 188), (709, 174), (709, 162), (689, 234), (689, 240), (689, 244), (691, 250), (691, 255), (702, 229), (703, 234), (703, 239), (703, 245), (703, 250)]
], dtype=np.float32)

points_2 = np.array([
    [(283, 231), (282, 220), (282, 210), (279, 198), (279, 185), (294, 227), (292, 218), (293, 205), (290, 195), (291, 183), (275, 245), (276, 251), (276, 253), (276, 257), (276, 261), (286, 243), (285, 246), (287, 250), (286, 253), (286, 257)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL16R03.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL16R03.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.87    0.01 -323.73]
 [   0.11    0.85  -34.03]]
Homography Matrix:
 [[ -0.30   0.01 235.50]
 [ -0.26   0.08 185.80]
 [ -0.00   0.00   1.00]]
Rotation Matrix R:
 [[-0.57 -0.82  0.00]
 [-0.82  0.57 -0.00]
 [-0.00 -0.00 -1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-83.06]
 [159.48]
 [ -0.24]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[3745.36]
 [2954.97]
 [  16.90]]


LEFT 17, RIGHT 04

In [5]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L17.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R04.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(679, 213), (678, 202), (677, 188), (676, 176), (676, 164), (691, 209), (690, 196), (689, 185), (688, 174), (689, 159), (695, 219), (696, 224), (696, 228), (696, 233), (696, 238), (707, 219), (709, 225), (709, 229), (711, 233), (709, 239)]
], dtype=np.float32)

points_2 = np.array([
    [(271, 228), (271, 217), (270, 207), (269, 195), (269, 183), (281, 225), (281, 213), (280, 204), (278, 192), (281, 179), (285, 234), (287, 237), (287, 239), (287, 242), (287, 247), (295, 230), (296, 233), (296, 236), (296, 238), (295, 242)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL17R04.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL17R04.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.87    0.00 -318.74]
 [  -0.02    0.89   51.93]]
Homography Matrix:
 [[ -0.48   0.01 317.88]
 [ -0.34  -0.03 232.87]
 [ -0.00   0.00   1.00]]
Rotation Matrix R:
 [[ 0.93 -0.36 -0.00]
 [ 0.36  0.93  0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.04]
 [-0.11]
 [21.05]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-10754.55]
 [ -7878.32]
 [   -34.83]]


LEFT 18, RIGHT 05

In [6]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L18.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R05.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(676, 212), (676, 200), (677, 186), (678, 175), (676, 161), (690, 213), (691, 199), (691, 187), (690, 174), (690, 163), (680, 224), (682, 229), (682, 233), (684, 238), (685, 242), (694, 228), (696, 231), (699, 237), (699, 242), (701, 246)]
], dtype=np.float32)

points_2 = np.array([
    [(281, 224), (281, 212), (281, 203), (280, 190), (279, 180), (291, 227), (291, 217), (291, 206), (290, 194), (290, 184), (284, 235), (285, 239), (285, 243), (287, 249), (287, 253), (294, 240), (294, 244), (296, 247), (297, 249), (298, 252)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL18R05.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL18R05.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.71    0.02 -203.22]
 [   0.21    0.87 -104.18]]
Homography Matrix:
 [[ -1.76  -0.62 940.64]
 [ -0.84  -1.57 596.50]
 [ -0.00  -0.00   1.00]]
Rotation Matrix R:
 [[ 0.94 -0.33 -0.00]
 [ 0.33  0.94 -0.00]
 [ 0.00  0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[ 0.01]
 [-0.06]
 [19.15]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-924.42]
 [-586.21]
 [  -1.98]]


LEFT 19, RIGHT 06

In [7]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L19.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R06.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(692, 220), (693, 206), (691, 191), (690, 179), (692, 165), (707, 221), (705, 209), (709, 193), (706, 181), (707, 169), (682, 227), (682, 232), (685, 237), (687, 242), (687, 247), (696, 231), (696, 236), (698, 240), (700, 243), (702, 250)]
], dtype=np.float32)

points_2 = np.array([
    [(277, 233), (277, 220), (277, 209), (276, 199), (275, 185), (289, 234), (287, 226), (287, 213), (289, 201), (288, 189), (271, 239), (271, 242), (271, 245), (271, 248), (271, 250), (281, 244), (281, 247), (281, 250), (281, 254), (284, 257)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL19R06.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL19R06.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.74   -0.02 -229.96]
 [   0.09    0.82  -11.46]]
Homography Matrix:
 [[ -0.02   0.16  92.49]
 [ -0.20   0.46 135.08]
 [ -0.00   0.00   1.00]]
Rotation Matrix R:
 [[ 0.06 -1.00  0.02]
 [-1.00 -0.06  0.01]
 [-0.00 -0.02 -1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-129.99]
 [ 122.96]
 [  -1.07]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[582.10]
 [850.21]
 [  7.29]]


LEFT 20, RIGHT 07

In [8]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L20.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R07.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(686, 225), (686, 212), (685, 197), (688, 186), (686, 173), (703, 230), (703, 215), (702, 203), (703, 189), (703, 174), (676, 235), (678, 239), (680, 244), (681, 249), (684, 254), (692, 239), (693, 246), (695, 249), (698, 253), (699, 258)]
], dtype=np.float32)

points_2 = np.array([
    [(281, 237), (280, 228), (280, 215), (279, 203), (279, 192), (292, 240), (292, 228), (292, 218), (292, 207), (292, 195), (273, 245), (275, 249), (274, 253), (276, 257), (277, 261), (285, 250), (286, 253), (287, 257), (287, 262), (290, 266)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL20R07.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL20R07.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.72    0.02 -221.57]
 [  -0.02    0.85   57.11]]
Homography Matrix:
 [[ -1.50  -0.26 808.71]
 [ -0.59  -1.04 396.39]
 [ -0.00  -0.00   1.00]]
Rotation Matrix R:
 [[ 0.96 -0.29 -0.00]
 [ 0.29  0.96 -0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.01]
 [-0.07]
 [16.65]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-972.84]
 [-476.84]
 [  -2.20]]


LEFT 21, RIGHT 08

In [9]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L21.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R08.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(661, 225), (661, 211), (664, 200), (663, 186), (663, 174), (676, 228), (677, 216), (677, 203), (675, 189), (679, 175), (653, 234), (654, 239), (656, 244), (657, 249), (659, 254), (668, 238), (671, 244), (674, 249), (675, 255), (676, 257)]
], dtype=np.float32)

points_2 = np.array([
    [(257, 236), (257, 226), (257, 214), (256, 202), (254, 189), (267, 239), (267, 227), (267, 218), (268, 206), (269, 194), (249, 245), (250, 249), (251, 253), (251, 258), (252, 262), (261, 250), (260, 253), (261, 258), (262, 262), (264, 266)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL21R08.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL21R08.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.66   -0.08 -161.44]
 [  -0.01    0.87   50.09]]
Homography Matrix:
 [[ -0.01  -0.16 126.51]
 [ -0.22   0.15 189.14]
 [ -0.00  -0.00   1.00]]
Rotation Matrix R:
 [[-0.11 -0.99  0.01]
 [-0.99  0.11  0.00]
 [-0.00 -0.01 -1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-120.04]
 [ 133.62]
 [  -0.12]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[516.95]
 [772.87]
 [  5.09]]


LEFT 22, RIGHT 09

In [10]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L22.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R09.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
     [(633, 225), (634, 213), (633, 200), (631, 187), (635, 174), (647, 230), (649, 217), (648, 205), (648, 192), (648, 177), (624, 235), (627, 241), (627, 243), (629, 248), (631, 252), (638, 239), (641, 242), (641, 247), (644, 252), (645, 258)]
], dtype=np.float32)

points_2 = np.array([
    [(235, 239), (237, 227), (236, 215), (236, 202), (234, 191), (246, 239), (246, 227), (246, 216), (248, 207), (245, 192), (225, 246), (226, 250), (228, 253), (229, 258), (232, 263), (237, 250), (239, 255), (240, 259), (241, 262), (243, 268)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL22R09.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL22R09.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.64   -0.03 -163.32]
 [  -0.15    0.95  117.30]]
Homography Matrix:
 [[    6.11    -2.95 -2124.45]
 [    2.09     1.65  -604.71]
 [    0.01    -0.01     1.00]]
Rotation Matrix R:
 [[-0.99 -0.14 -0.01]
 [-0.14  0.99 -0.01]
 [ 0.01 -0.01 -1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[  12.47]
 [-179.04]
 [   0.64]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-877.84]
 [-249.87]
 [   1.41]]
