LEFT 13, RIGHT 00

In [1]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L13.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R00.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(587, 71), (589, 89), (597, 80), (603, 65), (591, 107), (599, 95), (607, 82), (614, 71), (621, 58), (592, 124), (601, 112), (606, 101), (615, 89), (623, 77), (630, 66), (639, 53), (593, 141), (602, 130), (611, 118), (619, 106)]
], dtype=np.float32)

points_2 = np.array([
    [(178, 86), (183, 103), (189, 93), (197, 83), (185, 120), (192, 110), (199, 100), (205, 91), (213, 79), (188, 139), (196, 128), (203, 117), (209, 107), (216, 97), (223, 87), (228, 78), (192, 155), (198, 143), (205, 134), (211, 124)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL13R00.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL13R00.png', img1_warped_contrast)  # Warped Image 1 저장

# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.99    0.06 -408.39]
 [   0.17    0.94  -83.85]]
Homography Matrix:
 [[    50.20      3.77 -22890.03]
 [    12.21     38.71  -6665.47]
 [     0.06      0.01      1.00]]
Rotation Matrix R:
 [[ 0.98 -0.22 -0.00]
 [ 0.22  0.98 -0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.00]
 [-0.06]
 [12.57]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-632.65]
 [-184.22]
 [  -0.97]]


LEFT 14, RIGHT 01

In [3]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L14.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R01.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(556, 75), (561, 92), (568, 79), (575, 67), (561, 106), (569, 97), (577, 86), (584, 75), (592, 64), (564, 126), (572, 115), (579, 102), (589, 93), (594, 80), (602, 70), (611, 58), (567, 142), (574, 131), (582, 122), (590, 111)]
], dtype=np.float32)

points_2 = np.array([
    [(153, 84), (158, 101), (163, 91), (170, 82), (158, 120), (166, 109), (172, 101), (179, 89), (188, 79), (162, 137), (168, 128), (178, 118), (182, 108), (191, 97), (198, 88), (205, 76), (165, 155), (173, 145), (179, 134), (185, 124)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL14R01.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL14R01.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.97    0.02 -386.73]
 [   0.19    1.02  -97.12]]
Homography Matrix:
 [[   0.37   -0.02 -120.87]
 [   0.02    0.50   -3.91]
 [  -0.00   -0.00    1.00]]
Rotation Matrix R:
 [[-1.00 -0.01 -0.02]
 [-0.01  1.00 -0.00]
 [ 0.02 -0.00 -1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[   1.23]
 [-178.86]
 [   0.07]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-243.00]
 [  -7.86]
 [   3.01]]


LEFT 15, RIGHT 02

In [2]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L15.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R02.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(537, 76), (538, 92), (548, 82), (554, 71), (540, 111), (548, 101), (554, 89), (564, 76), (570, 64), (543, 126), (551, 116), (556, 104), (564, 95), (572, 82), (579, 70), (587, 60), (544, 143), (552, 132), (559, 120), (567, 111)]
], dtype=np.float32)

points_2 = np.array([
    [(129, 81), (132, 100), (140, 90), (148, 80), (136, 118), (144, 108), (151, 97), (158, 88), (165, 77), (140, 135), (146, 125), (152, 116), (160, 104), (168, 94), (175, 84), (180, 76), (143, 151), (149, 140), (157, 131), (164, 120)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees)")
print("라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL15R02.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL15R02.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   1.07    0.08 -449.57]
 [   0.19    1.01  -96.00]]
Homography Matrix:
 [[    7.79     0.62 -3481.86]
 [    1.81     6.11  -962.99]
 [    0.01     0.00     1.00]]
Rotation Matrix R:
 [[ 0.98 -0.21 -0.00]
 [ 0.21  0.98 -0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees)
라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.01]
 [-0.06]
 [12.17]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-606.73]
 [-167.81]
 [  -0.83]]


LEFT 16, RIGHT 03

In [3]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L16.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R03.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(513, 76), (513, 94), (522, 83), (528, 72), (518, 112), (525, 101), (532, 90), (539, 78), (545, 68), (520, 126), (528, 116), (533, 107), (541, 95), (548, 84), (554, 74), (562, 61), (522, 144), (528, 134), (536, 122), (544, 112)]
], dtype=np.float32)

points_2 = np.array([
    [(101, 77), (105, 97), (112, 85), (118, 76), (108, 115), (116, 104), (124, 94), (130, 84), (139, 73), (112, 132), (120, 121), (126, 112), (134, 101), (140, 91), (148, 80), (152, 72), (114, 149), (123, 138), (130, 129), (136, 120)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL16R03.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL16R03.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   1.10    0.03 -465.82]
 [   0.14    1.05  -74.41]]
Homography Matrix:
 [[   11.50     0.05 -5007.81]
 [    3.00     8.95 -1548.40]
 [    0.02    -0.00     1.00]]
Rotation Matrix R:
 [[ 0.97 -0.24 -0.00]
 [ 0.24  0.97  0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.03]
 [-0.08]
 [13.64]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-585.34]
 [-180.99]
 [  -0.88]]


LEFT 17, RIGHT 04

In [4]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L17.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R04.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(488, 79), (490, 97), (497, 84), (504, 72), (492, 112), (498, 101), (505, 90), (515, 78), (520, 67), (493, 129), (500, 119), (507, 108), (514, 98), (520, 85), (528, 75), (536, 63), (496, 144), (503, 134), (508, 124), (516, 113)]
], dtype=np.float32)

points_2 = np.array([
    [(73, 72), (77, 93), (84, 82), (94, 71), (83, 112), (88, 104), (97, 92), (105, 82), (113, 72), (86, 132), (92, 120), (100, 109), (107, 99), (114, 90), (120, 79), (128, 68), (89, 146), (96, 137), (103, 127), (109, 119)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL17R04.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL17R04.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   1.23    0.08 -530.44]
 [   0.33    1.07 -172.89]]
Homography Matrix:
 [[  -2.45   -0.13 1097.29]
 [  -0.94   -1.69  481.61]
 [  -0.01   -0.00    1.00]]
Rotation Matrix R:
 [[ 0.95 -0.32 -0.00]
 [ 0.32  0.95  0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.03]
 [-0.11]
 [18.87]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-733.50]
 [-321.94]
 [  -1.67]]


LEFT 18, RIGHT 05

In [5]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L18.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R05.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(667, 20), (667, 37), (672, 28), (681, 20), (668, 52), (674, 43), (680, 35), (688, 28), (696, 17), (668, 68), (674, 59), (682, 52), (689, 43), (698, 33), (706, 25), (715, 14), (668, 82), (675, 75), (683, 67), (689, 59)]
], dtype=np.float32)

points_2 = np.array([
    [(265, 54), (267, 68), (272, 61), (279, 53), (269, 82), (273, 76), (280, 70), (284, 63), (291, 56), (269, 95), (274, 89), (279, 84), (287, 76), (291, 70), (296, 64), (301, 58), (270, 110), (276, 104), (282, 98), (287, 93)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL18R05.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL18R05.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.84    0.05 -291.62]
 [   0.16    0.89  -74.00]]
Homography Matrix:
 [[ -0.74  -0.12 428.19]
 [ -0.18  -0.28 113.97]
 [ -0.00  -0.00   1.00]]
Rotation Matrix R:
 [[ 0.98 -0.20 -0.00]
 [ 0.20  0.98  0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.01]
 [-0.10]
 [11.45]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-1741.91]
 [ -463.63]
 [   -5.07]]


LEFT 19, RIGHT 06

In [6]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L19.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R06.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(656, 22), (655, 39), (662, 30), (668, 21), (655, 52), (662, 45), (668, 37), (676, 26), (684, 17), (653, 70), (663, 60), (668, 54), (676, 45), (684, 36), (693, 27), (699, 19), (655, 84), (660, 76), (668, 68), (677, 60)]
], dtype=np.float32)

points_2 = np.array([
    [(240, 52), (242, 66), (246, 60), (252, 53), (244, 82), (248, 76), (253, 68), (258, 63), (264, 55), (244, 95), (249, 88), (254, 82), (260, 76), (266, 70), (272, 63), (276, 56), (244, 108), (249, 104), (253, 98), (259, 92)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL19R06.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL19R06.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.78    0.06 -273.65]
 [   0.30    0.93 -168.48]]
Homography Matrix:
 [[ -13.31    1.23 6188.26]
 [  -3.10   -9.27 1701.82]
 [  -0.02    0.01    1.00]]
Rotation Matrix R:
 [[ 0.98 -0.21 -0.00]
 [ 0.21  0.98  0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.04]
 [-0.07]
 [12.06]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-667.10]
 [-183.46]
 [  -1.11]]


LEFT 20, RIGHT 07

In [7]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L20.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R07.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(621, 28), (621, 41), (629, 35), (636, 26), (621, 59), (629, 50), (633, 42), (640, 34), (651, 24), (622, 72), (629, 65), (636, 57), (642, 51), (651, 41), (658, 30), (664, 24), (624, 88), (628, 80), (636, 73), (642, 66)]
], dtype=np.float32)

points_2 = np.array([
    [(220, 48), (220, 62), (226, 58), (233, 52), (224, 80), (228, 73), (233, 67), (237, 62), (245, 52), (224, 96), (229, 89), (235, 82), (240, 75), (246, 68), (249, 64), (257, 56), (225, 107), (230, 101), (236, 96), (240, 91)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL20R07.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL20R07.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.87    0.06 -321.97]
 [   0.23    0.96 -119.83]]
Homography Matrix:
 [[ -0.89  -0.17 472.15]
 [ -0.23  -0.47 137.67]
 [ -0.00  -0.00   1.00]]
Rotation Matrix R:
 [[ 0.98 -0.21 -0.00]
 [ 0.21  0.98 -0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.01]
 [-0.11]
 [12.36]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-1158.72]
 [ -337.87]
 [   -3.45]]


LEFT 21, RIGHT 08

In [8]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L21.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R08.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
    [(600, 30), (598, 45), (604, 37), (615, 28), (600, 60), (606, 52), (612, 44), (620, 36), (628, 25), (599, 75), (605, 69), (612, 61), (619, 52), (627, 44), (635, 36), (641, 24), (600, 90), (605, 83), (612, 76), (620, 68)]
], dtype=np.float32)

points_2 = np.array([
    [(196, 49), (196, 62), (202, 57), (206, 50), (197, 76), (202, 72), (208, 64), (215, 58), (219, 51), (199, 92), (203, 86), (210, 79), (215, 72), (220, 66), (225, 60), (232, 53), (199, 105), (205, 100), (210, 95), (216, 88)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL21R08.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL21R08.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.84    0.06 -311.13]
 [   0.15    0.94  -71.85]]
Homography Matrix:
 [[   0.64   -0.25 -215.11]
 [   0.13    0.61  -55.13]
 [  -0.00   -0.00    1.00]]
Rotation Matrix R:
 [[ 0.98 -0.20 -0.00]
 [ 0.20  0.98  0.00]
 [-0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.15]
 [ 0.01]
 [11.44]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-326.39]
 [ -83.66]
 [   0.52]]


LEFT 22, RIGHT 09

In [9]:
import cv2
import numpy as np

# 이미지 파일 경로 설정
image1_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_L22.png'
image2_path = 'C:/Users/chaerim/OneDrive/Calibration/matching/matching/images/dog_edges_R09.png'

# 이미지 읽기
img1 = cv2.imread(image1_path)
img2 = cv2.imread(image2_path)

# 이미지 읽기 성공 여부 확인
if img1 is None:
    print(f"Error: Unable to load image at {image1_path}")
    exit()

if img2 is None:
    print(f"Error: Unable to load image at {image2_path}")
    exit()

# 이미지 크기
h, w = img2.shape[:2]  # img2의 크기를 사용하여 변환 이미지 크기를 맞춤

# 호모그래피 행렬 계산
points_1 = np.array([
     [(572, 32), (572, 47), (578, 38), (586, 30), (572, 63), (578, 55), (585, 48), (592, 40), (598, 31), (573, 76), (579, 71), (586, 64), (591, 56), (599, 48), (603, 41), (615, 29), (573, 91), (578, 85), (586, 76), (592, 69)]
], dtype=np.float32)

points_2 = np.array([
    [(172, 44), (172, 60), (179, 52), (185, 47), (174, 76), (179, 69), (185, 62), (191, 56), (196, 49), (175, 92), (180, 83), (186, 76), (192, 70), (198, 62), (203, 57), (209, 48), (175, 104), (180, 99), (188, 93), (192, 87)]
      ], dtype=np.float32)

# 아핀 변환 행렬 계산
affine_matrix, inliers = cv2.estimateAffine2D(points_1, points_2)

# 호모그래피 행렬 계산
H, status = cv2.findHomography(points_1, points_2, cv2.RANSAC)

# 호모그래피 행렬 분해
K = np.eye(3)  # 기본 카메라 행렬, 보통 아이덴티티 행렬로 사용
retval, R_list, t_list, n_list = cv2.decomposeHomographyMat(H, K)

# 첫 번째 해 (총 4개의 해가 있을 수 있음)
R = R_list[0]
t = t_list[0]

# 회전 행렬을 회전 벡터로 변환
rvec, _ = cv2.Rodrigues(R)

# 소수점 두 자리까지 표시
np.set_printoptions(precision=2, suppress=True, floatmode='fixed')

# 라디안 단위의 회전 벡터를 각도(도) 단위로 변환
rvec_degrees = np.degrees(rvec)

print("Affine Transformation Matrix:\n", affine_matrix)
print("Homography Matrix:\n", H)
print("Rotation Matrix R:\n", R)
print("Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:\n", rvec_degrees)
print("Translation Vector t (in pixels) 변환 벡터 t는 픽셀:\n", t)

# 이미지 1을 이미지 2의 좌표계로 변환 (Warping)
img1_warped = cv2.warpPerspective(img1, H, (w, h))

# 히스토그램 평활화 적용
if len(img1_warped.shape) == 3 and img1_warped.shape[2] == 3:
    img1_warped_gray = cv2.cvtColor(img1_warped, cv2.COLOR_BGR2GRAY)
    img1_warped_eq = cv2.equalizeHist(img1_warped_gray)
else:
    img1_warped_eq = cv2.equalizeHist(img1_warped)

# 대비 조정 적용
alpha = 1.5  # Contrast control (1.0-3.0)
beta = 0    # Brightness control (0-100)

img1_warped_contrast = cv2.convertScaleAbs(img1_warped_eq, alpha=alpha, beta=beta)

# img2를 그레이스케일로 변환하여 크기 및 채널 수를 맞춤
img2_gray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# 두 이미지 병합 (Blending) - 가중합 비율 50%
blend = cv2.addWeighted(img1_warped_contrast, 0.5, img2_gray, 0.5, 0)

# 결과 이미지 저장
cv2.imwrite('wraped_blended_images/blended_imageL22R09.png', blend)
cv2.imwrite('wraped_blended_images/warped_imageL22R09.png', img1_warped_contrast)  # Warped Image 1 저장


# 결과 이미지 표시
cv2.imshow('Warped Image 1', img1_warped_contrast)
cv2.imshow('Blended Image', blend)
cv2.waitKey(0)
cv2.destroyAllWindows()


Affine Transformation Matrix:
 [[   0.94    0.04 -367.08]
 [   0.18    1.01  -91.27]]
Homography Matrix:
 [[   1.28   -0.17 -507.29]
 [   0.29    1.15 -146.10]
 [   0.00   -0.00    1.00]]
Rotation Matrix R:
 [[ 0.98 -0.21 -0.00]
 [ 0.21  0.98  0.00]
 [ 0.00 -0.00  1.00]]
Rotation Vector (Rodrigues) rvec (in degrees) 라디안 단위의 회전 벡터를 각도(도) 단위로 변환:
 [[-0.06]
 [-0.03]
 [12.35]]
Translation Vector t (in pixels) 변환 벡터 t는 픽셀:
 [[-437.94]
 [-126.13]
 [  -0.14]]
